export const DICCIONARIO_BUSQUEDAS = {
  "Botillerías": [
    "botillería",
    "botilleria",
    "licores",
    "alcohol",
    "copete",
    "trago",
    "tragos",
    "ron",
    "pisco",
    "vodka",
    "whisky",
    "whiskey",
    "cerveza",
    "vino",
    "champaña",
    "espumante",
    "licor",
    "bebida alcohólica",
    "bebidas alcohólicas",
    "bebida",
    "bebidas",
    "gaseosa",
    "energética",
    "energéticas",
    "red bull",
    "monster",
    "speed",
    "cigarros",
    "tabaco",
    "mani",
    "maní",
    "papas fritas",
    "snack",
    "snacks",
    "mezclador",
    "mezcladores",
    "refresco",
    "refrescos",
    "bebestible",
    "bebestibles",
    "bebestible alcohólico",
    "bebestibles alcohólicos",
    "mezcla",
    "traguito",
    "ronda",
    "noche",
    "carrete",
    "chela"
  ],
  "Panaderías": [
    "panadería",
    "panaderia",
    "pan",
    "marraqueta",
    "hallulla",
    "molde",
    "baguette",
    "bollito",
    "pan amasado",
    "pan integral",
    "pan de molde",
    "pan francés",
    "pan batido",
    "pan dulce",
    "pan de campo",
    "pan pita",
    "pan ciabatta",
    "pan de centeno",
    "pan de avena",
    "pan de nuez",
    "pan de pasas",
    "pan de ajo",
    "pan de queso",
    "pan de cebolla",
    "pan de aceituna",
    "pan de orégano",
    "pastel",
    "pasteles",
    "torta",
    "galletas",
    "kuchen",
    "masa",
    "pan de yema",
    "pan con chicharrón"
  ],
  "Supermercados": [
    "supermercado",
    "super",
    "líder",
    "tottus",
    "acuenta",
    "unimarc",
    "jumbo",
    "santa isabel",
    "mercado",
    "hipermercado",
    "autoservicio",
    "minimarket",
    "mercadito",
    "almacén",
    "almacen",
    "tienda de barrio",
    "tienda de esquina",
    "tienda de víveres",
    "tienda de comestibles",
    "tienda de alimentos",
    "tienda de productos básicos",
    "pan",
    "azúcar",
    "arroz",
    "harina",
    "aceite",
    "leche",
    "queso",
    "jamón",
    "fiambres",
    "lácteos",
    "huevos",
    "yogur",
    "galletas",
    "jugos",
    "bebidas",
    "detergente",
    "cloro",
    "shampoo",
    "papel higiénico",
    "congelados",
    "snacks",
    "fideos",
    "legumbres",
    "salsas",
    "enlatados",
    "chocolates",
    "cereales",
    "comida para perros",
    "cepillos de dientes",
    "afeitadoras",
    "pañales",
    "pañuelos",
    "carne",
    "pollo",
    "pescado",
    "verduras",
    "frutas",
    "galletitas",
    "café",
    "té"
  ],
  "Verdulerías": [
    "verdulería",
    "verduleria",
    "verduras",
    "vegetales",
    "lechuga",
    "tomate",
    "cebolla",
    "papa",
    "papas",
    "zanahoria",
    "ajo",
    "pimentón",
    "pimenton",
    "pepino",
    "repollo",
    "coliflor",
    "brócoli",
    "brocoli",
    "espinaca",
    "acelga",
    "betarraga",
    "choclo",
    "poroto verde",
    "habas",
    "berenjena",
    "zapallo",
    "zapallito",
    "alcachofa",
    "espárrago",
    "esparrago",
    "rúcula",
    "rucula",
    "cilantro",
    "perejil",
    "albahaca",
    "cebollín",
    "cebollin",
    "cebolla morada",
    "cebolla blanca"
  ],
  "Carnicerías": [
    "carnicería",
    "carniceria",
    "carne",
    "vacuno",
    "res",
    "cerdo",
    "pollo",
    "pavo",
    "carne molida",
    "filete",
    "lomo",
    "costillar",
    "asado",
    "chuleta",
    "entraña",
    "punta de ganso",
    "punta picana",
    "posta",
    "posta negra",
    "posta rosada",
    "huachalomo",
    "plateada",
    "tapapecho",
    "sobrecostilla",
    "osobuco",
    "hueso carnudo",
    "longaniza",
    "chorizo",
    "salchicha",
    "salame",
    "jamón",
    "jamonada",
    "mortadela",
    "tocino",
    "bacon",
    "charqui"
  ],
  "Pizzerías": [
    "pizzería",
    "pizzeria",
    "pizza",
    "pizzas",
    "mozarella",
    "mozzarella",
    "pepperoni",
    "napolitana",
    "pizzas artesanales",
    "orégano",
    "oregano",
    "masa italiana",
    "pizza italiana",
    "pizza napolitana",
    "pizza pepperoni",
    "pizza vegetariana",
    "pizza de queso",
    "pizza de jamón",
    "pizza de champiñones",
    "pizza de pollo",
    "pizza de carne",
    "pizza de mariscos",
    "pizza de atún",
    "pizza de salame",
    "pizza de tocino",
    "pizza de cebolla",
    "pizza de aceitunas",
    "pizza de piña",
    "pizza hawaiana"
  ],
  "Pollerías": [
    "pollería",
    "polleria",
    "pollo",
    "pollo asado",
    "pollo broaster",
    "pollo frito",
    "presas de pollo",
    "alitas",
    "muslos",
    "pechuga",
    "trutro",
    "trutro corto",
    "trutro largo",
    "pollo al horno",
    "pollo a la brasa",
    "pollo apanado",
    "pollo crispy",
    "pollo grillado",
    "pollo al carbón",
    "pollo al spiedo"
  ],
  "Pastelerías": [
    "pastelería",
    "pasteleria",
    "pastel",
    "kuchen",
    "torta",
    "pie",
    "dulces",
    "brazo de reina",
    "galletas",
    "queque",
    "pastel de chocolate",
    "pastel de frutas",
    "pastel de manzana",
    "pastel de frambuesa",
    "pastel de lúcuma",
    "pastel de tres leches",
    "pastel de mil hojas",
    "pastel de hojaldre",
    "pastel de crema",
    "pastel de merengue",
    "pastel de chantilly",
    "pastel de manjar",
    "pastel de nuez",
    "pastel de almendra",
    "pastel de coco",
    "pastel de zanahoria",
    "pastel de piña"
  ],
  "Marisquerías": [
    "marisquería",
    "marisqueria",
    "mariscos",
    "locos",
    "ostiones",
    "piure",
    "jaiba",
    "choritos",
    "paila marina",
    "ceviche",
    "camarones",
    "pulpo",
    "calamar",
    "almejas",
    "machas",
    "navajuelas",
    "erizos",
    "centolla",
    "langosta",
    "langostinos",
    "congrio",
    "reineta",
    "merluza",
    "corvina",
    "salmon",
    "salmón",
    "tilapia",
    "trucha",
    "pescado frito",
    "pescado al horno",
    "pescado a la plancha"
  ],
  "Heladerías": [
    "heladería",
    "heladeria",
    "helado",
    "helados",
    "barquillo",
    "sundae",
    "paleta",
    "frutilla",
    "chocolate",
    "vainilla",
    "manjar",
    "lúcuma",
    "lucuma",
    "mango",
    "piña",
    "coco",
    "nuez",
    "almendra",
    "avellana",
    "menta",
    "limón",
    "limon",
    "naranja",
    "frambuesa",
    "arándano",
    "arandano",
    "maracuyá",
    "maracuya",
    "sandía",
    "sandia",
    "melón",
    "melon",
    "durazno",
    "plátano",
    "platano",
    "banana",
    "kiwi",
    "granizado",
    "sorbet",
    "sorbete"
  ],
  "Minimarkets": [
    "minimarket",
    "mini market",
    "minimercado",
    "tienda de barrio",
    "tienda de conveniencia",
    "almacén",
    "almacen",
    "tienda pequeña",
    "abarrotes",
    "snacks",
    "dulces",
    "golosinas",
    "bebidas",
    "gaseosas",
    "jugos",
    "agua mineral",
    "cervezas",
    "vinos",
    "licores",
    "pan",
    "galletas",
    "papas fritas",
    "mani",
    "maní",
    "chicles",
    "caramelos",
    "chocolates",
    "helados",
    "lácteos",
    "yogur",
    "leche",
    "queso",
    "jamón",
    "salchichas",
    "huevos",
    "aceite",
    "arroz",
    "fideos",
    "azúcar",
    "sal",
    "harina",
    "detergente",
    "jabón",
    "cloro",
    "papel higiénico",
    "toallas de papel",
    "servilletas",
    "bolsas de basura",
    "pilas",
    "encendedores",
    "fósforos",
    "pan de molde",
    "pan amasado",
    "pañales",
    "cepillo de dientes",
    "desodorante",
    "pañuelos",
    "café",
    "té",
    "salsa",
    "enlatados",
    "cereal"
  ],
  "Empanaderías": [
    "empanadería",
    "empanaderia",
    "empanadas",
    "empanada",
    "empanada de pino",
    "empanada de queso",
    "empanada de mariscos",
    "empanada de camarón",
    "empanada de napolitana",
    "empanada de pollo",
    "empanada de carne",
    "empanada de champiñones",
    "empanada de espinaca",
    "empanada de choclo",
    "empanada de jamón y queso",
    "empanada de atún",
    "empanada de cebolla",
    "empanada de aceituna",
    "empanada de huevo",
    "empanada de pasas",
    "empanada de ají",
    "empanada de merkén",
    "empanada horneada",
    "empanada frita",
    "masa de empanada",
    "empanadas caseras",
    "empanadas artesanales"
  ],
  "Comida china": [
    "comida china",
    "restaurante chino",
    "chino",
    "arroz chaufa",
    "chapsui",
    "chop suey",
    "rollito primavera",
    "wantán",
    "wonton",
    "pollo mongoliano",
    "cerdo agridulce",
    "fideos chinos",
    "sopa wantán",
    "arroz frito",
    "tallarines chinos",
    "chao mein",
    "empanaditas chinas",
    "salsa de soya",
    "soya",
    "sésamo",
    "sopa china",
    "comida asiática",
    "comida oriental"
  ],
  "Comida rápida": [
    "comida rápida",
    "fast food",
    "papas fritas",
    "hamburguesa",
    "nuggets",
    "hot dog",
    "completo",
    "vienesa",
    "sándwich",
    "sandwich",
    "wrap",
    "combo",
    "cheeseburger",
    "hamburguesa doble",
    "hamburguesa casera",
    "pollo crispy",
    "pollo frito",
    "menú rápido",
    "cajita feliz",
    "combo familiar",
    "salsas",
    "mostaza",
    "ketchup",
    "mayonesa"
  ],
  "Comida casera": [
    "comida casera",
    "almuerzo",
    "menú del día",
    "plato del día",
    "cazuela",
    "porotos",
    "lentejas",
    "carbonada",
    "charquicán",
    "arroz con pollo",
    "carne mechada",
    "pastel de choclo",
    "tomaticán",
    "tallarines",
    "porotos granados",
    "ensalada chilena",
    "sopaipillas",
    "pantrucas",
    "tortilla de papas",
    "estofado",
    "budín",
    "guatitas"
  ],
  "Comida mexicana": [
    "comida mexicana",
    "mexicana",
    "tacos",
    "burritos",
    "nachos",
    "quesadillas",
    "enchiladas",
    "guacamole",
    "salsa picante",
    "jalapeños",
    "frijoles",
    "salsa mexicana",
    "pico de gallo",
    "fajitas",
    "chili",
    "comida tex-mex"
  ],
  "Comida peruana": [
    "comida peruana",
    "ceviche",
    "lomo saltado",
    "ají de gallina",
    "papa a la huancaína",
    "chicha morada",
    "anticuchos",
    "rocoto",
    "tiradito",
    "tallarines verdes",
    "arroz chaufa",
    "causa limeña",
    "pollo a la brasa",
    "comida criolla"
  ],
  "Sushi / Japonesa": [
    "sushi",
    "sushi rolls",
    "rolls",
    "makis",
    "nigiri",
    "sashimi",
    "temaki",
    "uramaki",
    "hosomaki",
    "soya",
    "wasabi",
    "jengibre",
    "palillos",
    "arroz para sushi",
    "vinagre de arroz",
    "sake",
    "algas",
    "comida japonesa"
  ],
  "Comida tailandesa": [
    "comida tailandesa",
    "thai",
    "pad thai",
    "curry rojo",
    "curry verde",
    "curry amarillo",
    "arroz jazmín",
    "sopa tom yum",
    "leche de coco",
    "noodles",
    "tallarines tailandeses",
    "comida asiática"
  ],
  "Comida árabe": [
    "comida árabe",
    "shawarma",
    "falafel",
    "hummus",
    "kebab",
    "pan pita",
    "tabulé",
    "berenjena",
    "yogur árabe",
    "carne al palo",
    "empanadas árabes",
    "salsas árabes",
    "garbanzos",
    "tajine"
  ],
  "Comida italiana": [
    "comida italiana",
    "italiana",
    "pasta",
    "spaghetti",
    "espagueti",
    "lasaña",
    "fettuccine",
    "carbonara",
    "boloñesa",
    "alfredo",
    "pesto",
    "macarrones",
    "gnocchi",
    "ñoquis",
    "ravioles",
    "canelones",
    "pizza",
    "pan de ajo",
    "queso parmesano",
    "mozzarella",
    "caprese",
    "tiramisú",
    "bruschetta"
  ],
  "Comida vegana / vegetariana": [
    "vegano",
    "vegetariano",
    "comida vegana",
    "comida vegetariana",
    "hamburguesa vegana",
    "ensalada",
    "tofu",
    "lentejas",
    "quinoa",
    "proteína vegetal",
    "sin carne",
    "sin lácteos",
    "sin huevo",
    "plant based",
    "vegetales salteados",
    "sopa de verduras",
    "batidos verdes",
    "arroz integral",
    "leche vegetal",
    "soja",
    "soya",
    "productos orgánicos",
    "comida saludable"
  ],
  "Cafeterías / teterías": [
    "cafetería",
    "café",
    "cafe",
    "capuchino",
    "latte",
    "americano",
    "espresso",
    "café helado",
    "macchiato",
    "mocha",
    "frappé",
    "té",
    "tetería",
    "infusiones",
    "matcha",
    "chai",
    "tisana",
    "té verde",
    "té negro",
    "té de hierbas",
    "té con miel",
    "desayuno",
    "croissant",
    "bizcocho",
    "muffin",
    "brownie"
  ],
  "Locales de completos / hot dogs": [
    "completo",
    "completos",
    "hot dog",
    "vienesa",
    "italiano",
    "dinámico",
    "luco",
    "barros luco",
    "completo con palta",
    "completo con chucrut",
    "sándwich de vienesa",
    "completo italiano",
    "completo dinámico",
    "ketchup",
    "mayonesa",
    "mostaza",
    "palta",
    "chucrut",
    "ají",
    "salsa verde",
    "pan de completo",
    "pan de hot dog"
  ],
  "Restaurantes familiares": [
    "restaurante familiar",
    "comida familiar",
    "almuerzo",
    "plato del día",
    "cena",
    "desayuno",
    "comida casera",
    "comida típica",
    "restaurante chileno",
    "cazuela",
    "empanadas",
    "porotos",
    "comida abundante",
    "menú del día",
    "tenedor libre",
    "restaurant tradicional",
    "comida para compartir",
    "local amplio",
    "local familiar"
  ],
  "Kioscos / Snacks": [
    "kiosco",
    "snack",
    "snacks",
    "papas fritas",
    "ramitas",
    "chicles",
    "golosinas",
    "dulces",
    "galletas",
    "barritas",
    "alfajor",
    "super 8",
    "trululu",
    "chocman",
    "gomitas",
    "mani",
    "maní",
    "jugos",
    "bebidas",
    "helados",
    "juguetes pequeños",
    "sorpresas",
    "trompos",
    "stickers"
  ],
  "Tiendas de abarrotes": [
    "abarrotes",
    "tienda de abarrotes",
    "almacén",
    "almacen",
    "tienda de barrio",
    "productos básicos",
    "arroz",
    "fideos",
    "azúcar",
    "harina",
    "aceite",
    "leche",
    "café",
    "té",
    "sal",
    "salsa",
    "conservas",
    "legumbres",
    "enlatados",
    "galletas",
    "detergente",
    "papel higiénico",
    "productos de limpieza",
    "comestibles",
    "víveres",
    "snacks",
    "jugos",
    "productos no perecibles"
  ],
  "Tiendas naturistas": [
    "naturista",
    "productos naturales",
    "productos orgánicos",
    "semillas",
    "chia",
    "linaza",
    "quinoa",
    "maca",
    "avena",
    "almendras",
    "nueces",
    "frutas secas",
    "arándanos deshidratados",
    "superalimentos",
    "multivitamínicos",
    "leche vegetal",
    "té detox",
    "fitoterapia",
    "alimentos sin gluten",
    "productos sin azúcar",
    "probióticos",
    "aceites esenciales",
    "tinturas madres"
  ],
  "Tiendas de productos de limpieza": [
    "productos de limpieza",
    "limpieza",
    "detergente",
    "lavalozas",
    "cloro",
    "desinfectante",
    "limpiavidrios",
    "jabón líquido",
    "escobas",
    "traperos",
    "guantes",
    "esponjas",
    "papel higiénico",
    "toallas de papel",
    "ambientador",
    "limpia piso",
    "limpia baño",
    "limpia cocina",
    "pulidor",
    "desengrasante",
    "virutilla",
    "sarro",
    "blanqueador",
    "bicarbonato",
    "limpieza ecológica"
  ],
  "Bazar y librerías": [
    "bazar",
    "librería",
    "libros",
    "cuadernos",
    "lápices",
    "reglas",
    "goma",
    "sacapuntas",
    "cartulinas",
    "adhesivos",
    "stickers",
    "papelería",
    "material escolar",
    "juguetes pequeños",
    "estuches",
    "libretas",
    "útiles escolares",
    "lapiceras",
    "marcadores",
    "bolígrafos",
    "resaltadores",
    "pizarras",
    "tijeras",
    "bazar chino",
    "todo a mil",
    "regalos",
    "peluches",
    "tarjetas",
    "variedades"
  ],
  "Tiendas de artículos para el hogar": [
    "hogar",
    "artículos para el hogar",
    "vajilla",
    "ollas",
    "sartenes",
    "cubiertos",
    "platos",
    "vasos",
    "manteles",
    "almohadas",
    "cortinas",
    "cojines",
    "ropa de cama",
    "organizadores",
    "escobas",
    "trapeadores",
    "baldes",
    "bandejas",
    "adornos",
    "decoración",
    "floreros",
    "repisas",
    "percheros",
    "utensilios",
    "termos",
    "jarras",
    "vasijas",
    "frascos",
    "fuentes",
    "tazas",
    "posavasos",
    "mesas plegables"
  ],
  "Tiendas de artículos médicos y ortopédicos": [
    "artículos médicos",
    "ortopedia",
    "muletas",
    "bastones",
    "sillas de ruedas",
    "andadores",
    "collarín",
    "faja lumbar",
    "tensiómetro",
    "oxímetro",
    "termómetro",
    "medicinas",
    "suplementos médicos",
    "plantillas ortopédicas",
    "prótesis",
    "cabestrillo",
    "vendas",
    "parches",
    "silla para ducha",
    "pastillas",
    "equipo médico",
    "botiquín",
    "tiras reactivas"
  ],
  "Tiendas de regalos": [
    "regalos",
    "souvenirs",
    "peluches",
    "tarjetas",
    "decoraciones",
    "cajas sorpresa",
    "detalles",
    "regalos personalizados",
    "tazas con mensaje",
    "flores",
    "bombones",
    "dulces",
    "velas decorativas",
    "artesanías",
    "postales",
    "juguetes para regalo",
    "papel de regalo",
    "moños",
    "globos",
    "llaveros"
  ],
  "Tiendas de manualidades y cordonería": [
    "manualidades",
    "cordonería",
    "hilos",
    "lana",
    "botones",
    "cintas",
    "cierres",
    "pegamento",
    "tijeras",
    "pintura acrílica",
    "pinceles",
    "papel crepé",
    "foami",
    "cartulina",
    "mostacillas",
    "canutillos",
    "palitos de helado",
    "stencil",
    "telas",
    "costura",
    "bordado",
    "crochet",
    "macramé",
    "artesanía",
    "diseño manual",
    "fieltro"
  ],
  "Papelerías": [
    "papelería",
    "papeleria",
    "papel",
    "cuadernos",
    "folios",
    "impresión",
    "anillado",
    "copias",
    "carpetas",
    "tapas plásticas",
    "hojas",
    "papel fotográfico",
    "papel autocopia",
    "papel carta",
    "papel oficio",
    "papel bond",
    "papel reciclado",
    "encuadernación",
    "servicios de impresión",
    "copias blanco y negro",
    "fotocopias",
    "trabajos escolares"
  ],
  "Tiendas de tecnología y electrónica": [
    "tecnología",
    "electrónica",
    "audífonos",
    "parlantes",
    "cargadores",
    "mouse",
    "teclado",
    "pantalla",
    "monitor",
    "notebook",
    "tablet",
    "pc",
    "pantalla led",
    "accesorios electrónicos",
    "usb",
    "powerbank",
    "batería externa",
    "lector de tarjeta",
    "reproductores",
    "bluetooth",
    "hub usb",
    "cables hdmi",
    "gadgets"
  ],
  "Tiendas electrónicas / accesorios de celular": [
    "accesorios de celular",
    "celular",
    "carcasas",
    "protectores de pantalla",
    "micas",
    "cargadores",
    "auriculares",
    "bluetooth",
    "parlantes portátiles",
    "lentes para celular",
    "trípodes",
    "anillos de agarre",
    "soportes de auto",
    "cargador inalámbrico",
    "batería celular",
    "memoria micro sd",
    "usb",
    "pin de chip",
    "cable tipo c",
    "accesorios samsung",
    "accesorios iphone"
  ],
  "Tiendas de computación / reparación PC": [
    "computación",
    "reparación de pc",
    "servicio técnico",
    "notebook",
    "computador",
    "instalación de software",
    "formateo",
    "teclado",
    "mouse",
    "pantalla",
    "disco duro",
    "ssd",
    "memoria ram",
    "cables",
    "fuente de poder",
    "torre",
    "placa madre",
    "pasta térmica",
    "monitores",
    "pantalla externa",
    "gabinetes",
    "refrigeración líquida",
    "gaming"
  ],
  "Tiendas de juegos / hobbies / coleccionismo": [
    "juegos",
    "juguetes",
    "cartas",
    "figuras coleccionables",
    "rompecabezas",
    "juegos de mesa",
    "lego",
    "monopoly",
    "ajedrez",
    "damas",
    "dardos",
    "naipes",
    "cartas magic",
    "pokémon",
    "funko pop",
    "modelismo",
    "maquetas",
    "drones",
    "autos a control remoto",
    "pistas",
    "ferromodelismo",
    "trompos",
    "hobbies creativos",
    "armables"
  ],
  "Tiendas de vestuario infantil": [
    "ropa infantil",
    "niños",
    "niñas",
    "ropa para bebés",
    "ropa para niños",
    "ropa para niñas",
    "polerones",
    "poleras",
    "pantalones",
    "jeans",
    "vestidos",
    "conjuntos",
    "pijamas",
    "zapatillas niños",
    "zapatos escolares",
    "calzas",
    "ropa cómoda",
    "ropa escolar",
    "ropa de temporada",
    "ropa interior infantil",
    "mamelucos",
    "baberos"
  ],
  "Tiendas de vestuario femenino": [
    "ropa mujer",
    "ropa femenina",
    "blusas",
    "poleras",
    "tops",
    "crop tops",
    "polerones",
    "chaquetas",
    "abrigos",
    "vestidos",
    "faldas",
    "jeans",
    "pantalones",
    "leggings",
    "calzas",
    "enteritos",
    "ropa casual",
    "ropa elegante",
    "ropa de oficina",
    "ropa formal",
    "ropa informal",
    "zapatillas",
    "botas",
    "tacones",
    "zapatos mujer",
    "ropa de moda",
    "outfits",
    "ropa para mujer joven",
    "vestimenta femenina",
    "moda femenina",
    "trajes de dos piezas"
  ],
  "Tiendas de ropa masculina": [
    "ropa hombre",
    "ropa masculina",
    "camisas",
    "poleras",
    "pantalones",
    "bermudas",
    "jeans",
    "shorts",
    "chaquetas",
    "blazers",
    "trajes",
    "ropa formal",
    "ropa casual",
    "ropa deportiva",
    "ropa interior hombre",
    "boxers",
    "calzoncillos",
    "zapatillas hombre",
    "zapatos de vestir",
    "chalecos",
    "parkas",
    "sweaters",
    "polerones",
    "moda masculina"
  ],
  "Tiendas de segunda mano / reciclaje": [
    "segunda mano",
    "ropa usada",
    "ropa reciclada",
    "ropa vintage",
    "ropa retro",
    "economía circular",
    "trueque",
    "reciclaje",
    "ropa americana",
    "bazares usados",
    "feria americana",
    "tienda de segunda mano",
    "usados",
    "outlet",
    "ropa reacondicionada",
    "tienda ecológica",
    "reciclado",
    "tienda sustentable",
    "productos reutilizados"
  ],
  "Tiendas de lencería / ropa interior": [
    "lencería",
    "ropa interior",
    "calzones",
    "sostenes",
    "panties",
    "brasier",
    "boxer",
    "ropa íntima",
    "ropa interior mujer",
    "ropa interior hombre",
    "baby doll",
    "pijamas íntimos",
    "corset",
    "ropa sexy",
    "ropa interior de encaje",
    "ropa interior algodón",
    "tops deportivos",
    "ropa para dormir",
    "ropa de noche"
  ],
  "Joyerías y relojerías": [
    "joyería",
    "relojería",
    "anillos",
    "collares",
    "pulseras",
    "aros",
    "aretes",
    "pendientes",
    "joyas",
    "relojes",
    "reloj pulsera",
    "reloj inteligente",
    "cadenas",
    "dijes",
    "medallas",
    "bisutería",
    "joyas de plata",
    "joyas de oro",
    "joyas de acero",
    "joyas personalizadas",
    "estuches para joyas",
    "cadenas con nombre"
  ],
  "Ópticas": [
    "óptica",
    "lentes",
    "anteojos",
    "gafas",
    "lentes ópticos",
    "lentes de sol",
    "lentes recetados",
    "marcos",
    "cristales ópticos",
    "óptico",
    "lentes bifocales",
    "lentes multifocales",
    "lentes de contacto",
    "soluciones ópticas",
    "limpiador de lentes",
    "examen visual",
    "optometría",
    "control visual",
    "gafas modernas",
    "lentes transparentes"
  ],
  "Farmacias": [
    "farmacia",
    "remedios",
    "medicamentos",
    "pastillas",
    "ibuprofeno",
    "paracetamol",
    "aspirina",
    "antigripales",
    "jarabe",
    "vitaminas",
    "antibióticos",
    "analgésicos",
    "pomadas",
    "cremas",
    "termómetro",
    "condones",
    "test de embarazo",
    "gasas",
    "alcohol gel",
    "mascarillas",
    "suplementos",
    "prescripción",
    "receta médica",
    "farmacia de turno"
  ],
  "Centros de estética / peluquerías / barberías": [
    "peluquería",
    "barbería",
    "estética",
    "salón de belleza",
    "corte de pelo",
    "tinte",
    "alisado",
    "keratina",
    "mechas",
    "barba",
    "afeitado",
    "peinado",
    "planchado de pelo",
    "manicure",
    "pedicure",
    "uñas acrílicas",
    "uñas gel",
    "depilación",
    "cejas",
    "pestañas",
    "masajes",
    "tratamientos faciales",
    "estilista",
    "look",
    "peinados de fiesta"
  ],
  "Tiendas de cosméticos y cuidado personal": [
    "cosméticos",
    "maquillaje",
    "base",
    "labial",
    "rimel",
    "sombra",
    "rubor",
    "iluminador",
    "esmalte de uñas",
    "cosmética natural",
    "cremas",
    "lociones",
    "aceites",
    "serum",
    "productos faciales",
    "shampoo",
    "acondicionador",
    "gel",
    "jabón",
    "perfume",
    "cuidado de la piel",
    "bloqueador",
    "toallitas desmaquillantes"
  ],
  "Ferreterías": [
    "ferretería",
    "clavos",
    "martillo",
    "destornillador",
    "tornillos",
    "cemento",
    "silicona",
    "taladro",
    "brocas",
    "esmeril",
    "sierra",
    "llave inglesa",
    "atornillador",
    "alicate",
    "cinta aisladora",
    "pegamento",
    "mangueras",
    "grifos",
    "fierro",
    "madera",
    "tubo PVC",
    "tornillo rosca",
    "herrajes",
    "cerraduras",
    "candados",
    "pintura",
    "rodillo",
    "brocha",
    "escalera"
  ],
  "Talleres mecánicos / lubricentros": [
    "mecánico",
    "taller mecánico",
    "lubricentro",
    "cambio de aceite",
    "revisión técnica",
    "afinamiento",
    "diagnóstico",
    "batería",
    "motor",
    "frenos",
    "balanceo",
    "alineación",
    "reparación de autos",
    "taller automotriz",
    "servicio técnico vehicular",
    "scanner automotriz",
    "revisión de embrague",
    "fugas de aceite",
    "radiador",
    "luces",
    "neumáticos",
    "parabrisas",
    "amortiguadores",
    "revisión de bujías",
    "escape",
    "filtro de aire"
  ],
  "Tiendas de repuestos / autopartes": [
    "repuestos",
    "autopartes",
    "amortiguadores",
    "batería auto",
    "focos",
    "lámparas",
    "espejos",
    "retrovisores",
    "parachoques",
    "parrillas",
    "pastillas de freno",
    "discos de freno",
    "bujías",
    "embrague",
    "filtro de aceite",
    "filtro de aire",
    "filtro de bencina",
    "aceite de motor",
    "liquido de frenos",
    "accesorios auto",
    "limpiaparabrisas",
    "tapiz",
    "llantas",
    "tapas de ruedas",
    "neumáticos",
    "kit de distribución",
    "soporte motor",
    "cojinetes"
  ],
  "Tiendas de mascotas": [
    "mascotas",
    "tienda de mascotas",
    "alimento para perros",
    "alimento para gatos",
    "comida para mascotas",
    "arena sanitaria",
    "collares",
    "correas",
    "arnés",
    "ropa para mascotas",
    "juguetes para mascotas",
    "camas para mascotas",
    "rascadores",
    "snacks para mascotas",
    "productos veterinarios",
    "vitaminas para perros",
    "antipulgas",
    "champú para mascotas",
    "cepillos",
    "comedero",
    "bebedero",
    "jaulas",
    "peceras",
    "accesorios mascotas"
  ],
  "Tiendas de outdoor y camping": [
    "camping",
    "outdoor",
    "carpas",
    "sacos de dormir",
    "linternas",
    "botellas térmicas",
    "morrales",
    "mochilas de camping",
    "cocina de camping",
    "sillas plegables",
    "mesas plegables",
    "hornillos",
    "parrillas portátiles",
    "tiendas de campaña",
    "colchonetas inflables",
    "ropa outdoor",
    "bastones de trekking",
    "gafas deportivas",
    "calzado outdoor",
    "fogatas portátiles",
    "iluminación camping",
    "compás",
    "brújula",
    "repelente"
  ],
  "Tiendas de deporte y fitness": [
    "deporte",
    "fitness",
    "pesas",
    "mancuernas",
    "bandas elásticas",
    "ropa deportiva",
    "zapatillas deportivas",
    "bicicleta estática",
    "bicicleta spinning",
    "barras olímpicas",
    "pelotas de yoga",
    "colchonetas",
    "ropa de gimnasio",
    "guantes deportivos",
    "shaker",
    "proteínas",
    "suplementos deportivos",
    "entrenamiento funcional",
    "implementos deportivos",
    "pesas rusas",
    "máquinas de ejercicio",
    "elíptica",
    "cinta de correr"
  ],
  "Tiendas de bicicletas / talleres": [
    "bicicleta",
    "bicicletas",
    "taller bicicleta",
    "reparación de bicicleta",
    "bicicleta de montaña",
    "bicicleta urbana",
    "bicicleta eléctrica",
    "repuestos bicicleta",
    "llaves allen",
    "bombín",
    "inflador",
    "pedales",
    "cadenas",
    "frenos",
    "casco",
    "guantes",
    "maillots",
    "portabotellas",
    "alforjas",
    "luces para bicicleta",
    "soporte celular",
    "parlante bicicleta",
    "pata de apoyo"
  ],
  "Tiendas de fotografía y accesorios": [
    "fotografía",
    "tienda de fotografía",
    "cámaras",
    "cámaras réflex",
    "cámaras mirrorless",
    "lentes fotográficos",
    "trípode",
    "estabilizador",
    "memoria sd",
    "lector de tarjetas",
    "estudios fotográficos",
    "fondos",
    "softbox",
    "filtros",
    "drones con cámara",
    "selfie stick",
    "batería cámara",
    "flash",
    "impresora fotográfica",
    "revelado",
    "marcos para fotos",
    "álbumes"
  ],
  "Tiendas de decoración y diseño": [
    "decoración",
    "diseño interior",
    "cuadros",
    "murales",
    "lámparas decorativas",
    "jarrones",
    "plantas artificiales",
    "floreros",
    "velas decorativas",
    "alfombras",
    "cortinas decorativas",
    "estanterías",
    "repisas",
    "percheros de diseño",
    "espejos",
    "cojines",
    "portavelas",
    "difusores decorativos",
    "maceteros",
    "objetos decorativos",
    "centros de mesa"
  ],
  "Tiendas de aromaterapia / esencias / velas": [
    "aromaterapia",
    "esencias",
    "velas aromáticas",
    "incienso",
    "difusores",
    "aceites esenciales",
    "ambientadores",
    "quemadores de esencias",
    "varitas de incienso",
    "resinas aromáticas",
    "velas naturales",
    "velas de soja",
    "aceite de lavanda",
    "aceite de eucalipto",
    "aceite de menta",
    "relajación",
    "bienestar",
    "spa en casa",
    "roll on",
    "spray ambiental"
  ]
}