export const DICCIONARIO_BUSQUEDAS = {
  "Botillerías": [
    "botillería",
    "botilleria",
    "licores",
    "alcohol",
    "copete",
    "trago",
    "tragos",
    "ron",
    "pisco",
    "vodka",
    "whisky",
    "whiskey",
    "cerveza",
    "vino",
    "champaña",
    "espumante",
    "licor",
    "bebida alcohólica",
    "bebidas alcohólicas",
    "bebida",
    "bebidas",
    "gaseosa",
    "energética",
    "energéticas",
    "red bull",
    "monster",
    "speed",
    "cigarros",
    "tabaco",
    "mani",
    "maní",
    "papas fritas",
    "snack",
    "snacks",
    "mezclador",
    "mezcladores",
    "refresco",
    "refrescos",
    "bebestible",
    "bebestibles",
    "bebestible alcohólico",
    "bebestibles alcohólicos",
    "mezcla",
    "traguito",
    "ronda",
    "noche",
    "carrete",
    "chela"
  ],
  "Panaderías": [
    "panadería",
    "panaderia",
    "pan",
    "marraqueta",
    "hallulla",
    "molde",
    "baguette",
    "bollito",
    "pan amasado",
    "pan integral",
    "pan de molde",
    "pan francés",
    "pan batido",
    "pan dulce",
    "pan de campo",
    "pan pita",
    "pan ciabatta",
    "pan de centeno",
    "pan de avena",
    "pan de nuez",
    "pan de pasas",
    "pan de ajo",
    "pan de queso",
    "pan de cebolla",
    "pan de aceituna",
    "pan de orégano",
    "pastel",
    "pasteles",
    "torta",
    "galletas",
    "kuchen",
    "masa",
    "pan de yema",
    "pan con chicharrón"
  ],
  ...
}
